// 100-pose library for Outline Rush — 11 hand-made classics followed by
// procedurally generated poses. DO NOT EDIT BY HAND: regenerate with
//   node scripts/generate-poses.mjs
// Angles per skeleton.js: 0 = down, 90 = out, 180 = up, negative/>180 = inward.

const POSES = [
  {name: "Star Jump", emoji: "⭐", tip: "Arms up and out, legs wide!", difficulty: 1, arms: {L: [135, 140], R: [135, 140]}, legs: {L: [20, 22], R: [20, 22]}},
  {name: "T-Pose", emoji: "✈️", tip: "Arms straight out, feet together.", difficulty: 1, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [4, 4], R: [4, 4]}},
  {name: "Muscle Flex", emoji: "💪", tip: "Flex both arms like a strongman!", difficulty: 1, arms: {L: [95, 205], R: [95, 205]}, legs: {L: [10, 10], R: [10, 10]}},
  {name: "Disco Fever", emoji: "🕺", tip: "Point to the sky, hand on hip!", difficulty: 2, arms: {L: [55, -35], R: [150, 155]}, legs: {L: [18, 20], R: [4, 4]}},
  {name: "Invisible Chair", emoji: "🪑", tip: "Squat like you are sitting, arms out!", difficulty: 2, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [38, -12], R: [38, -12]}},
  {name: "Flamingo", emoji: "🦩", tip: "One leg tucked in, arms up in a V!", difficulty: 2, arms: {L: [140, 145], R: [140, 145]}, legs: {L: [2, 2], R: [62, -58]}},
  {name: "The Egyptian", emoji: "🏺", tip: "Arms in a zigzag — walk like an Egyptian!", difficulty: 2, arms: {L: [90, 170], R: [90, 10]}, legs: {L: [14, 15], R: [4, 4]}},
  {name: "Teapot", emoji: "🫖", tip: "Handle on the hip, spout out — and TIP!", difficulty: 2, arms: {L: [55, -35], R: [120, 55]}, legs: {L: [8, 8], R: [8, 8]}, lean: 12},
  {name: "Karate Crane", emoji: "🥋", tip: "Hands high, knee up — hii-ya!", difficulty: 3, arms: {L: [155, 160], R: [155, 160]}, legs: {L: [3, 3], R: [85, 8]}},
  {name: "Tipsy Tightrope", emoji: "🎪", tip: "Cross those legs, arms out, don't fall!", difficulty: 3, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [-14, -16], R: [-24, -26]}, lean: 7},
  {name: "Leaning Tower", emoji: "🗼", tip: "Arms up, tilt over… don't topple!", difficulty: 3, arms: {L: [168, 170], R: [168, 170]}, legs: {L: [2, 2], R: [2, 2]}, lean: 14},
  {name: "Mountain Pose", emoji: "🧘", tip: "Stand tall, feet together, arms at your sides — breathe.", difficulty: 1, arms: {L: [8, 6], R: [8, 6]}, legs: {L: [3, 3], R: [3, 3]}},
  {name: "Upward Salute", emoji: "🙆", tip: "Feet together, sweep both arms high overhead!", difficulty: 1, arms: {L: [172, 174], R: [172, 174]}, legs: {L: [3, 3], R: [3, 3]}},
  {name: "Five-Pointed Star", emoji: "⭐", tip: "Legs wide, arms wide — be a big star!", difficulty: 1, arms: {L: [118, 120], R: [118, 120]}, legs: {L: [22, 24], R: [22, 24]}},
  {name: "Chair Pose", emoji: "🪑", tip: "Sit back into a chair, arms reaching up!", difficulty: 2, arms: {L: [165, 168], R: [165, 168]}, legs: {L: [40, -14], R: [40, -14]}},
  {name: "Goddess Pose", emoji: "👑", tip: "Wide squat, bend your arms like a cactus!", difficulty: 2, arms: {L: [95, 168], R: [95, 168]}, legs: {L: [52, -24], R: [52, -24]}},
  {name: "Garland Squat", emoji: "🙏", tip: "Squat down deep, palms together at your heart.", difficulty: 2, arms: {L: [40, -30], R: [40, -30]}, legs: {L: [56, -36], R: [56, -36]}},
  {name: "Crescent Lunge", emoji: "🌙", tip: "Deep lunge, both arms reaching for the sky!", difficulty: 2, arms: {L: [170, 172], R: [170, 172]}, legs: {L: [46, -24], R: [8, 8]}},
  {name: "Warrior One", emoji: "🛡️", tip: "Lunge forward, sweep both arms overhead!", difficulty: 2, arms: {L: [166, 170], R: [166, 170]}, legs: {L: [34, -16], R: [10, 10]}},
  {name: "Warrior Two", emoji: "⚔️", tip: "Wide stance, bend the front knee, arms straight out!", difficulty: 2, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [42, -18], R: [18, 16]}},
  {name: "Tree Pose", emoji: "🌳", tip: "Foot to your inner thigh, palms together up high!", difficulty: 3, arms: {L: [178, 180], R: [178, 180]}, legs: {L: [3, 3], R: [58, -74]}},
  {name: "Eagle Pose", emoji: "🦅", tip: "Wrap your arms, cross your legs, sink down!", difficulty: 3, arms: {L: [74, 120], R: [70, 108]}, legs: {L: [-16, -14], R: [-30, -26]}},
  {name: "Triangle Pose", emoji: "📐", tip: "Wide legs, tip sideways — one arm up, one down!", difficulty: 3, arms: {L: [22, 18], R: [166, 170]}, legs: {L: [20, 22], R: [18, 20]}, lean: 20},
  {name: "Extended Side Angle", emoji: "🔺", tip: "Wide lunge, top arm reaching over your head!", difficulty: 3, arms: {L: [30, 22], R: [150, 160]}, legs: {L: [44, -20], R: [18, 16]}, lean: 22},
  {name: "Half Moon", emoji: "🌗", tip: "Balance on one leg, top leg out, reach up and down!", difficulty: 3, arms: {L: [10, 8], R: [172, 174]}, legs: {L: [3, 3], R: [92, 88]}, lean: 12},
  {name: "Dancer Pose", emoji: "💃", tip: "Lift your back foot, reach the other arm forward!", difficulty: 3, arms: {L: [150, 156], R: [64, 40]}, legs: {L: [3, 3], R: [46, 150]}, lean: 10},
  {name: "Airplane Balance", emoji: "✈️", tip: "Balance on one leg, other leg back, arms like wings!", difficulty: 3, arms: {L: [88, 88], R: [88, 88]}, legs: {L: [3, 3], R: [84, 74]}, lean: 8},
  {name: "Standing Splits", emoji: "🤸", tip: "One leg sky-high, reach down for the floor!", difficulty: 3, arms: {L: [16, 10], R: [16, 10]}, legs: {L: [3, 3], R: [124, 116]}},
  {name: "Figure-Four Chair", emoji: "🕊️", tip: "Cross one ankle over your knee and sit down!", difficulty: 3, arms: {L: [40, -28], R: [40, -28]}, legs: {L: [26, -12], R: [54, -104]}},
  {name: "Standing Hand-to-Toe", emoji: "🦶", tip: "Stand on one leg, extend the other straight out!", difficulty: 3, arms: {L: [90, 90], R: [50, -30]}, legs: {L: [3, 3], R: [94, 90]}},
  {name: "Warrior Three", emoji: "🕴️", tip: "Tip forward on one leg, arms and back leg reaching!", difficulty: 3, arms: {L: [128, 130], R: [128, 130]}, legs: {L: [3, 3], R: [70, 66]}, lean: 20},
  {name: "The Mystic Mantis", emoji: "🦗", tip: "Feet together, one flex, one sky-point!", difficulty: 2, arms: {L: [90, 204], R: [155, 154]}, legs: {L: [6, 5], R: [6, 5]}},
  {name: "The Lazy Lobster", emoji: "🦞", tip: "Feet together, cross your arms overhead!", difficulty: 2, arms: {L: [211, 212], R: [211, 212]}, legs: {L: [5, 5], R: [5, 5]}},
  {name: "The Heroic Flamingo", emoji: "🦩", tip: "Feet together, arms straight out!", difficulty: 1, arms: {L: [92, 89], R: [92, 89]}, legs: {L: [3, 4], R: [3, 4]}},
  {name: "The Feral Windmill", emoji: "🌀", tip: "Feet together, arms up in a V!", difficulty: 1, arms: {L: [140, 138], R: [140, 138]}, legs: {L: [6, 5], R: [6, 5]}},
  {name: "The Lazy Sasquatch", emoji: "🦶", tip: "Feet together, reach for the stars, and lean right!", difficulty: 2, arms: {L: [169, 178], R: [169, 178]}, legs: {L: [3, 4], R: [3, 4]}, lean: 12},
  {name: "The Glorious Traffic Cone", emoji: "🚧", tip: "Feet together, hands on hips!", difficulty: 1, arms: {L: [59, -32], R: [59, -32]}, legs: {L: [4, 5], R: [4, 5]}},
  {name: "The Heroic Goose", emoji: "🪿", tip: "Legs wide, hands on hips!", difficulty: 1, arms: {L: [55, -36], R: [55, -36]}, legs: {L: [19, 21], R: [19, 21]}},
  {name: "The Dramatic Giraffe", emoji: "🦒", tip: "Legs wide, point to the sky, hand on hip, and lean left!", difficulty: 3, arms: {L: [54, -40], R: [155, 161]}, legs: {L: [17, 24], R: [17, 24]}, lean: -14},
  {name: "The Grumpy Ninja", emoji: "🥷", tip: "Legs wide, point to the sky, hand on hip!", difficulty: 2, arms: {L: [151, 156], R: [56, -39]}, legs: {L: [23, 22], R: [23, 22]}},
  {name: "The Sleepy Banana", emoji: "🍌", tip: "Legs wide, arms low and wide, and lean right!", difficulty: 2, arms: {L: [37, 48], R: [37, 48]}, legs: {L: [20, 21], R: [20, 21]}, lean: 9},
  {name: "The Turbo Gremlin", emoji: "👹", tip: "Legs wide, hands down between your knees, and lean right!", difficulty: 2, arms: {L: [18, -11], R: [18, -11]}, legs: {L: [18, 22], R: [18, 22]}, lean: 8},
  {name: "The Awkward Gremlin", emoji: "👹", tip: "Legs wide, arms straight out, and lean left!", difficulty: 2, arms: {L: [91, 91], R: [91, 91]}, legs: {L: [17, 25], R: [17, 25]}, lean: -8},
  {name: "The Royal Wizard", emoji: "🧙", tip: "Deep warrior lunge, one arm up, one out!", difficulty: 3, arms: {L: [168, 173], R: [91, 92]}, legs: {L: [16, 11], R: [42, -14]}},
  {name: "The Funky Yeti", emoji: "❄️", tip: "Deep warrior lunge, one arm up, one out, and lean left!", difficulty: 3, arms: {L: [168, 168], R: [91, 88]}, legs: {L: [12, 12], R: [40, -17]}, lean: -14},
  {name: "The Disco Goose", emoji: "🪿", tip: "Deep warrior lunge, tilt your wings, and lean right!", difficulty: 3, arms: {L: [67, 72], R: [117, 119]}, legs: {L: [12, 12], R: [38, -16]}, lean: 13},
  {name: "The Turbo Cactus", emoji: "🌵", tip: "Deep warrior lunge, point to the sky, hand on hip!", difficulty: 3, arms: {L: [155, 158], R: [53, -32]}, legs: {L: [13, 11], R: [37, -17]}},
  {name: "The Slippery Kettle", emoji: "☕", tip: "Deep warrior lunge, point to the sky, hand on hip, and lean left!", difficulty: 3, arms: {L: [150, 163], R: [59, -37]}, legs: {L: [43, -15], R: [14, 13]}, lean: -11},
  {name: "The Cosmic Mantis", emoji: "🦗", tip: "Deep warrior lunge, one hand to the sky, one to the floor, and lean right!", difficulty: 3, arms: {L: [22, 23], R: [170, 175]}, legs: {L: [15, 13], R: [37, -20]}, lean: 8},
  {name: "The Tipsy Lobster", emoji: "🦞", tip: "Deep warrior lunge, one flex, one sky-point, and lean right!", difficulty: 3, arms: {L: [155, 159], R: [89, 210]}, legs: {L: [40, -22], R: [15, 12]}, lean: 14},
  {name: "The Sleepy Mantis", emoji: "🦗", tip: "Deep warrior lunge, arms up in a V!", difficulty: 2, arms: {L: [140, 136], R: [140, 136]}, legs: {L: [40, -18], R: [13, 11]}},
  {name: "The Grumpy Llama", emoji: "🦙", tip: "Squat down, one flex, one sky-point!", difficulty: 2, arms: {L: [90, 210], R: [158, 154]}, legs: {L: [35, -16], R: [35, -16]}},
  {name: "The Chaotic Starfish", emoji: "⭐", tip: "Squat down, goalpost arms, and lean left!", difficulty: 2, arms: {L: [88, 162], R: [88, 162]}, legs: {L: [40, -17], R: [40, -17]}, lean: -10},
  {name: "The Spicy Gremlin", emoji: "👹", tip: "Squat down, hands on hips!", difficulty: 2, arms: {L: [58, -34], R: [58, -34]}, legs: {L: [36, -13], R: [36, -13]}},
  {name: "The Slippery Meerkat", emoji: "🐿️", tip: "Squat down, palms together overhead like a prayer!", difficulty: 2, arms: {L: [179, 183], R: [179, 183]}, legs: {L: [44, -12], R: [44, -12]}},
  {name: "The Majestic Llama", emoji: "🦙", tip: "Squat down, cross your arms overhead!", difficulty: 2, arms: {L: [206, 214], R: [206, 214]}, legs: {L: [41, -18], R: [41, -18]}},
  {name: "The Electric Toad", emoji: "🐸", tip: "Squat down, cross your arms overhead, and lean left!", difficulty: 3, arms: {L: [198, 214], R: [198, 214]}, legs: {L: [37, -11], R: [37, -11]}, lean: -9},
  {name: "The Awkward Disco Ball", emoji: "🪩", tip: "Squat down, one hand to the sky, one to the floor!", difficulty: 2, arms: {L: [166, 173], R: [23, 25]}, legs: {L: [34, -14], R: [34, -14]}},
  {name: "The Galactic Traffic Cone", emoji: "🚧", tip: "Squat down, arms low and wide!", difficulty: 2, arms: {L: [36, 53], R: [36, 53]}, legs: {L: [36, -18], R: [36, -18]}},
  {name: "The Crispy Meerkat", emoji: "🐿️", tip: "Goddess squat, knees way out, one hand to the sky, one to the floor, and lean left!", difficulty: 3, arms: {L: [27, 21], R: [170, 170]}, legs: {L: [57, -24], R: [57, -24]}, lean: -9},
  {name: "The Galactic Cactus", emoji: "🌵", tip: "Goddess squat, knees way out, one hand to the sky, one to the floor!", difficulty: 3, arms: {L: [27, 24], R: [166, 169]}, legs: {L: [54, -21], R: [54, -21]}},
  {name: "The Spooky Llama", emoji: "🦙", tip: "Goddess squat, knees way out, arms straight out!", difficulty: 2, arms: {L: [89, 90], R: [89, 90]}, legs: {L: [51, -20], R: [51, -20]}},
  {name: "The Sleepy Jellyfish", emoji: "🪼", tip: "Goddess squat, knees way out, one arm up, one out!", difficulty: 3, arms: {L: [169, 171], R: [90, 91]}, legs: {L: [59, -23], R: [59, -23]}},
  {name: "The Feral Broccoli", emoji: "🥦", tip: "Goddess squat, knees way out, arms up in a V!", difficulty: 2, arms: {L: [156, 163], R: [156, 163]}, legs: {L: [59, -25], R: [59, -25]}},
  {name: "The Funky Disco Ball", emoji: "🪩", tip: "Goddess squat, knees way out, hands down between your knees, and lean right!", difficulty: 3, arms: {L: [20, -8], R: [20, -8]}, legs: {L: [49, -31], R: [49, -31]}, lean: 8},
  {name: "The Spicy Windmill", emoji: "🌀", tip: "Goddess squat, knees way out, hands down between your knees!", difficulty: 2, arms: {L: [19, -11], R: [19, -11]}, legs: {L: [55, -27], R: [55, -27]}},
  {name: "The Mystic Jellyfish", emoji: "🪼", tip: "Goddess squat, knees way out, flex those biceps!", difficulty: 2, arms: {L: [94, 211], R: [94, 211]}, legs: {L: [48, -28], R: [48, -28]}},
  {name: "The Royal Goose", emoji: "🪿", tip: "Crouch right down like a frog, cross your arms overhead, and lean right!", difficulty: 3, arms: {L: [202, 209], R: [202, 209]}, legs: {L: [61, -37], R: [61, -37]}, lean: 8},
  {name: "The Electric Disco Ball", emoji: "🪩", tip: "Crouch right down like a frog, reach for the stars, and lean right!", difficulty: 3, arms: {L: [176, 174], R: [176, 174]}, legs: {L: [60, -37], R: [60, -37]}, lean: 6},
  {name: "The Crispy Noodle", emoji: "🍜", tip: "Crouch right down like a frog, hands down between your knees!", difficulty: 3, arms: {L: [19, -17], R: [19, -17]}, legs: {L: [65, -34], R: [65, -34]}},
  {name: "The Slippery Giraffe", emoji: "🦒", tip: "Crouch right down like a frog, hands down between your knees!", difficulty: 3, arms: {L: [14, -11], R: [14, -11]}, legs: {L: [59, -34], R: [59, -34]}},
  {name: "The Turbo Goose", emoji: "🪿", tip: "Crouch right down like a frog, point to the sky, hand on hip!", difficulty: 3, arms: {L: [151, 160], R: [54, -39]}, legs: {L: [64, -35], R: [64, -35]}},
  {name: "The Disco Sasquatch", emoji: "🦶", tip: "Crouch right down like a frog, hands on hips!", difficulty: 3, arms: {L: [55, -34], R: [55, -34]}, legs: {L: [65, -30], R: [65, -30]}},
  {name: "The Funky Banana", emoji: "🍌", tip: "Cross your legs, hands on hips!", difficulty: 2, arms: {L: [58, -31], R: [58, -31]}, legs: {L: [-14, -17], R: [-26, -29]}},
  {name: "The Heroic Banana", emoji: "🍌", tip: "Cross your legs, arms low and wide!", difficulty: 2, arms: {L: [49, 48], R: [49, 48]}, legs: {L: [-28, -29], R: [-12, -17]}},
  {name: "The Confused Llama", emoji: "🦙", tip: "Cross your legs, tilt your wings, and lean right!", difficulty: 3, arms: {L: [72, 67], R: [107, 111]}, legs: {L: [-27, -28], R: [-15, -17]}, lean: 10},
  {name: "The Spooky Ninja", emoji: "🥷", tip: "Cross your legs, one flex, one sky-point!", difficulty: 3, arms: {L: [88, 207], R: [156, 161]}, legs: {L: [-23, -29], R: [-14, -15]}},
  {name: "The Legendary Meerkat", emoji: "🐿️", tip: "Cross your legs, point to the sky, hand on hip!", difficulty: 3, arms: {L: [154, 162], R: [54, -36]}, legs: {L: [-14, -16], R: [-24, -26]}},
  {name: "The Bendy Disco Ball", emoji: "🪩", tip: "Cross your legs, flex those biceps, and lean right!", difficulty: 3, arms: {L: [94, 208], R: [94, 208]}, legs: {L: [-12, -17], R: [-25, -25]}, lean: 7},
  {name: "The Bendy Wizard", emoji: "🧙", tip: "Cross your legs, goalpost arms, and lean left!", difficulty: 3, arms: {L: [90, 165], R: [90, 165]}, legs: {L: [-13, -16], R: [-23, -27]}, lean: -9},
  {name: "The Heroic Windmill", emoji: "🌀", tip: "Foot tucked to your knee, cross your arms overhead!", difficulty: 3, arms: {L: [209, 208], R: [209, 208]}, legs: {L: [68, -54], R: [3, 3]}},
  {name: "The Grumpy Ostrich", emoji: "🪶", tip: "Foot tucked to your knee, palms together overhead like a prayer, and lean right!", difficulty: 3, arms: {L: [181, 180], R: [181, 180]}, legs: {L: [64, -51], R: [1, 0]}, lean: 7},
  {name: "The Spicy Sasquatch", emoji: "🦶", tip: "Foot tucked to your knee, hands down between your knees!", difficulty: 2, arms: {L: [17, -14], R: [17, -14]}, legs: {L: [64, -49], R: [2, 0]}},
  {name: "The Turbo Sasquatch", emoji: "🦶", tip: "Foot tucked to your knee, arms low and wide!", difficulty: 2, arms: {L: [43, 47], R: [43, 47]}, legs: {L: [64, -55], R: [4, 3]}},
  {name: "The Crispy Starfish", emoji: "⭐", tip: "Foot tucked to your knee, cross your arms overhead!", difficulty: 3, arms: {L: [200, 217], R: [200, 217]}, legs: {L: [2, 4], R: [61, -55]}},
  {name: "The Lazy Ostrich", emoji: "🪶", tip: "Foot tucked to your knee, one hand to the sky, one to the floor!", difficulty: 3, arms: {L: [172, 172], R: [29, 22]}, legs: {L: [1, 2], R: [67, -57]}},
  {name: "The Awkward Robot", emoji: "🤖", tip: "Foot tucked to your knee, arms straight out, and lean left!", difficulty: 3, arms: {L: [90, 89], R: [90, 89]}, legs: {L: [59, -53], R: [1, 4]}, lean: -8},
  {name: "The Awkward Giraffe", emoji: "🦒", tip: "Foot tucked to your knee, arms up in a V, and lean right!", difficulty: 3, arms: {L: [136, 161], R: [136, 161]}, legs: {L: [4, 3], R: [63, -55]}, lean: 7},
  {name: "The Chaotic Noodle", emoji: "🍜", tip: "Foot tucked to your knee, palms together overhead like a prayer, and lean right!", difficulty: 3, arms: {L: [182, 181], R: [182, 181]}, legs: {L: [3, 2], R: [62, -48]}, lean: 8},
  {name: "The Funky Ninja", emoji: "🥷", tip: "Foot tucked to your knee, zigzag arms!", difficulty: 3, arms: {L: [89, 12], R: [91, 165]}, legs: {L: [1, 3], R: [63, -61]}},
  {name: "The Mystic Ninja", emoji: "🥷", tip: "Knee up high, flex those biceps, and lean left!", difficulty: 3, arms: {L: [98, 205], R: [98, 205]}, legs: {L: [84, 13], R: [4, 4]}, lean: -7},
  {name: "The Slippery Crab", emoji: "🦀", tip: "Knee up high, hands on hips!", difficulty: 2, arms: {L: [54, -31], R: [54, -31]}, legs: {L: [3, 4], R: [86, 11]}},
  {name: "The Dramatic Banana", emoji: "🍌", tip: "Knee up high, arms up in a V!", difficulty: 2, arms: {L: [143, 164], R: [143, 164]}, legs: {L: [4, 5], R: [90, 8]}},
  {name: "The Disco Heron", emoji: "🐦", tip: "Knee up high, point to the sky, hand on hip, and lean left!", difficulty: 3, arms: {L: [56, -39], R: [149, 154]}, legs: {L: [88, 13], R: [4, 4]}, lean: -6},
  {name: "The Majestic Ostrich", emoji: "🪶", tip: "Knee up high, cross your arms overhead, and lean left!", difficulty: 3, arms: {L: [200, 220], R: [200, 220]}, legs: {L: [87, 13], R: [5, 4]}, lean: -6},
  {name: "The Wobbly Pretzel", emoji: "🥨", tip: "Knee up high, arms low and wide!", difficulty: 2, arms: {L: [48, 44], R: [48, 44]}, legs: {L: [91, 11], R: [4, 3]}},
  {name: "The Confused Gremlin", emoji: "👹", tip: "Knee up high, one arm up, one out!", difficulty: 3, arms: {L: [91, 90], R: [163, 167]}, legs: {L: [5, 2], R: [86, 6]}},
  {name: "The Glorious Gremlin", emoji: "👹", tip: "Knee up high, hands on hips, and lean right!", difficulty: 3, arms: {L: [60, -33], R: [60, -33]}, legs: {L: [2, 4], R: [95, 9]}, lean: 7},
  {name: "The Cosmic Penguin", emoji: "🐧", tip: "Knee up high, one hand to the sky, one to the floor, and lean right!", difficulty: 3, arms: {L: [24, 24], R: [166, 172]}, legs: {L: [94, 11], R: [3, 4]}, lean: 7},
  {name: "The Confused Traffic Cone", emoji: "🚧", tip: "Knee up high, reach for the stars, and lean left!", difficulty: 3, arms: {L: [170, 174], R: [170, 174]}, legs: {L: [4, 5], R: [86, 13]}, lean: -6},
  {name: "The Sleepy Heron", emoji: "🐦", tip: "Kick a leg out to the side, hands on hips!", difficulty: 3, arms: {L: [55, -35], R: [55, -35]}, legs: {L: [4, 3], R: [83, 86]}, extreme: true},
  {name: "The Lazy Windmill", emoji: "🌀", tip: "Kick a leg out to the side, flex those biceps!", difficulty: 3, arms: {L: [92, 213], R: [92, 213]}, legs: {L: [4, 4], R: [83, 87]}, extreme: true},
  {name: "The Turbo Scarecrow", emoji: "🎃", tip: "Kick a leg out to the side, arms straight out!", difficulty: 3, arms: {L: [92, 92], R: [92, 92]}, legs: {L: [80, 86], R: [3, 5]}, extreme: true},
  {name: "The Disco Broccoli", emoji: "🥦", tip: "Kick a leg out to the side, cross your arms overhead!", difficulty: 3, arms: {L: [200, 207], R: [200, 207]}, legs: {L: [81, 86], R: [3, 3]}, extreme: true},
  {name: "The Tipsy Goose", emoji: "🪿", tip: "Kick a leg out to the side, tilt your wings!", difficulty: 3, arms: {L: [66, 69], R: [105, 115]}, legs: {L: [2, 3], R: [88, 74]}, extreme: true},
  {name: "The Legendary Crab", emoji: "🦀", tip: "Kick a leg out to the side, one hand to the sky, one to the floor!", difficulty: 3, arms: {L: [29, 26], R: [168, 172]}, legs: {L: [75, 75], R: [5, 5]}, extreme: true},
  {name: "The Confused Banana", emoji: "🍌", tip: "Kick your leg sky-high, one flex, one sky-point!", difficulty: 3, arms: {L: [92, 203], R: [155, 156]}, legs: {L: [98, 101], R: [5, 4]}, extreme: true},
  {name: "The Feral Goose", emoji: "🪿", tip: "Kick your leg sky-high, reach for the stars!", difficulty: 3, arms: {L: [172, 177], R: [172, 177]}, legs: {L: [4, 4], R: [106, 107]}, extreme: true},
  {name: "The Confused Ostrich", emoji: "🪶", tip: "Kick your leg sky-high, reach for the stars!", difficulty: 3, arms: {L: [169, 172], R: [169, 172]}, legs: {L: [4, 3], R: [99, 105]}, extreme: true},
  {name: "The Feral Heron", emoji: "🐦", tip: "Kick your leg sky-high, tilt your wings!", difficulty: 3, arms: {L: [115, 120], R: [64, 72]}, legs: {L: [4, 4], R: [110, 106]}, extreme: true},
  {name: "The Feral Meerkat", emoji: "🐿️", tip: "Kick your leg sky-high, arms straight out!", difficulty: 3, arms: {L: [92, 90], R: [92, 90]}, legs: {L: [102, 98], R: [3, 4]}, extreme: true},
  {name: "The Spicy Penguin", emoji: "🐧", tip: "Turn sideways, sprinter knee drive, hands down between your knees!", difficulty: 3, arms: {L: [17, -17], R: [17, -17]}, legs: {L: [78, -26], R: [5, 6]}, extreme: true},
  {name: "The Crispy Crab", emoji: "🦀", tip: "Turn sideways, sprinter knee drive, tilt your wings!", difficulty: 3, arms: {L: [64, 64], R: [111, 109]}, legs: {L: [82, -23], R: [3, 5]}, extreme: true},
  {name: "The Wonky Heron", emoji: "🐦", tip: "Turn sideways, sprinter knee drive, one hand to the sky, one to the floor!", difficulty: 3, arms: {L: [170, 169], R: [27, 18]}, legs: {L: [80, -29], R: [4, 6]}, extreme: true},
  {name: "The Spooky Pirate", emoji: "🏴‍☠️", tip: "Turn sideways, sprinter knee drive, arms low and wide!", difficulty: 3, arms: {L: [49, 46], R: [49, 46]}, legs: {L: [5, 5], R: [78, -29]}, extreme: true},
  {name: "The Bendy Pirate", emoji: "🏴‍☠️", tip: "JUMP and tuck as the timer hits zero, one arm up, one out!", difficulty: 3, arms: {L: [88, 90], R: [169, 166]}, legs: {L: [57, -28], R: [57, -28]}, air: 0.05, extreme: true},
  {name: "The Confused Pretzel", emoji: "🥨", tip: "JUMP and tuck as the timer hits zero, palms together overhead like a prayer!", difficulty: 3, arms: {L: [180, 180], R: [180, 180]}, legs: {L: [61, -34], R: [61, -34]}, air: 0.08, extreme: true},
  {name: "The Sneaky Llama", emoji: "🦙", tip: "JUMP and tuck as the timer hits zero, zigzag arms!", difficulty: 3, arms: {L: [88, 172], R: [91, 14]}, legs: {L: [53, -37], R: [53, -37]}, air: 0.05, extreme: true},
  {name: "The Wobbly Gremlin", emoji: "👹", tip: "JUMP into a star as the timer hits zero, one arm up, one out!", difficulty: 3, arms: {L: [163, 168], R: [91, 91]}, legs: {L: [27, 29], R: [27, 29]}, air: 0.07, extreme: true},
  {name: "The Tipsy Traffic Cone", emoji: "🚧", tip: "JUMP into a star as the timer hits zero, goalpost arms!", difficulty: 3, arms: {L: [92, 174], R: [92, 174]}, legs: {L: [27, 26], R: [27, 26]}, air: 0.06, extreme: true},
];
