// 100-pose library for Outline Rush — 11 hand-made classics followed by
// procedurally generated poses. DO NOT EDIT BY HAND: regenerate with
//   node scripts/generate-poses.mjs
// Angles per skeleton.js: 0 = down, 90 = out, 180 = up, negative/>180 = inward.

const POSES = [
  {name: "Star Jump", emoji: "⭐", tip: "Arms up and out, legs wide!", difficulty: 1, arms: {L: [135, 140], R: [135, 140]}, legs: {L: [20, 22], R: [20, 22]}},
  {name: "T-Pose", emoji: "✈️", tip: "Arms straight out, feet together.", difficulty: 1, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [4, 4], R: [4, 4]}},
  {name: "Muscle Flex", emoji: "💪", tip: "Flex both arms like a strongman!", difficulty: 1, arms: {L: [95, 205], R: [95, 205]}, legs: {L: [10, 10], R: [10, 10]}},
  {name: "Disco Fever", emoji: "🕺", tip: "Point to the sky, hand on hip!", difficulty: 2, arms: {L: [55, -35], R: [150, 155]}, legs: {L: [18, 20], R: [4, 4]}},
  {name: "Invisible Chair", emoji: "🪑", tip: "Squat like you are sitting, arms out!", difficulty: 2, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [38, -12], R: [38, -12]}},
  {name: "Flamingo", emoji: "🦩", tip: "One leg tucked in, arms up in a V!", difficulty: 2, arms: {L: [140, 145], R: [140, 145]}, legs: {L: [2, 2], R: [62, -58]}},
  {name: "The Egyptian", emoji: "🏺", tip: "Arms in a zigzag — walk like an Egyptian!", difficulty: 2, arms: {L: [90, 170], R: [90, 10]}, legs: {L: [14, 15], R: [4, 4]}},
  {name: "Teapot", emoji: "🫖", tip: "Handle on the hip, spout out — and TIP!", difficulty: 2, arms: {L: [55, -35], R: [120, 55]}, legs: {L: [8, 8], R: [8, 8]}, lean: 12},
  {name: "Karate Crane", emoji: "🥋", tip: "Hands high, knee up — hii-ya!", difficulty: 3, arms: {L: [155, 160], R: [155, 160]}, legs: {L: [3, 3], R: [85, 8]}},
  {name: "Tipsy Tightrope", emoji: "🎪", tip: "Cross those legs, arms out, don't fall!", difficulty: 3, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [-14, -16], R: [-24, -26]}, lean: 7},
  {name: "Leaning Tower", emoji: "🗼", tip: "Arms up, tilt over… don't topple!", difficulty: 3, arms: {L: [168, 170], R: [168, 170]}, legs: {L: [2, 2], R: [2, 2]}, lean: 14},
  {name: "The Mystic Mantis", emoji: "🦗", tip: "Feet together, one arm up, one out!", difficulty: 2, arms: {L: [164, 168], R: [90, 88]}, legs: {L: [6, 5], R: [6, 5]}},
  {name: "The Lazy Lobster", emoji: "🦞", tip: "Feet together, arms low and wide!", difficulty: 1, arms: {L: [49, 47], R: [49, 47]}, legs: {L: [5, 5], R: [5, 5]}},
  {name: "The Heroic Flamingo", emoji: "🦩", tip: "Feet together, arms up in a V!", difficulty: 1, arms: {L: [156, 145], R: [156, 145]}, legs: {L: [3, 4], R: [3, 4]}},
  {name: "The Feral Windmill", emoji: "🌀", tip: "Feet together, arms up in a V!", difficulty: 1, arms: {L: [140, 138], R: [140, 138]}, legs: {L: [6, 5], R: [6, 5]}},
  {name: "The Lazy Sasquatch", emoji: "🦶", tip: "Feet together, zigzag arms!", difficulty: 2, arms: {L: [89, 174], R: [90, 6]}, legs: {L: [3, 4], R: [3, 4]}},
  {name: "The Glorious Traffic Cone", emoji: "🚧", tip: "Feet together, flex those biceps!", difficulty: 1, arms: {L: [99, 213], R: [99, 213]}, legs: {L: [4, 5], R: [4, 5]}},
  {name: "The Heroic Goose", emoji: "🪿", tip: "Feet together, flex those biceps!", difficulty: 1, arms: {L: [96, 205], R: [96, 205]}, legs: {L: [3, 3], R: [3, 3]}},
  {name: "The Angry Cactus", emoji: "🌵", tip: "Feet together, hands on hips!", difficulty: 1, arms: {L: [54, -40], R: [54, -40]}, legs: {L: [2, 5], R: [2, 5]}},
  {name: "The Confused Cactus", emoji: "🌵", tip: "Feet together, reach for the stars!", difficulty: 1, arms: {L: [172, 176], R: [172, 176]}, legs: {L: [6, 4], R: [6, 4]}},
  {name: "The Grumpy Robot", emoji: "🤖", tip: "Feet together, arms straight out!", difficulty: 1, arms: {L: [90, 89], R: [90, 89]}, legs: {L: [3, 3], R: [3, 3]}},
  {name: "The Angry Yeti", emoji: "❄️", tip: "Feet together, one flex, one sky-point, and lean right!", difficulty: 3, arms: {L: [158, 152], R: [89, 205]}, legs: {L: [2, 4], R: [2, 4]}, lean: 11},
  {name: "The Glorious Gremlin", emoji: "👹", tip: "Legs wide, flex those biceps, and lean left!", difficulty: 2, arms: {L: [97, 206], R: [97, 206]}, legs: {L: [17, 20], R: [17, 20]}, lean: -13},
  {name: "The Galactic Sasquatch", emoji: "🦶", tip: "Legs wide, flex those biceps!", difficulty: 1, arms: {L: [93, 212], R: [93, 212]}, legs: {L: [22, 18], R: [22, 18]}},
  {name: "The Legendary Penguin", emoji: "🐧", tip: "Legs wide, reach for the stars!", difficulty: 1, arms: {L: [174, 177], R: [174, 177]}, legs: {L: [18, 18], R: [18, 18]}},
  {name: "The Sneaky Yeti", emoji: "❄️", tip: "Legs wide, zigzag arms!", difficulty: 2, arms: {L: [90, 166], R: [90, 7]}, legs: {L: [21, 21], R: [21, 21]}},
  {name: "The Wobbly Yeti", emoji: "❄️", tip: "Legs wide, goalpost arms!", difficulty: 1, arms: {L: [94, 166], R: [94, 166]}, legs: {L: [17, 23], R: [17, 23]}},
  {name: "The Glorious Wizard", emoji: "🧙", tip: "Legs wide, arms up in a V!", difficulty: 1, arms: {L: [151, 162], R: [151, 162]}, legs: {L: [17, 23], R: [17, 23]}},
  {name: "The Tipsy Goose", emoji: "🪿", tip: "Legs wide, tilt your wings!", difficulty: 2, arms: {L: [62, 69], R: [111, 112]}, legs: {L: [19, 25], R: [19, 25]}},
  {name: "The Haunted Sasquatch", emoji: "🦶", tip: "Legs wide, reach for the stars!", difficulty: 1, arms: {L: [172, 172], R: [172, 172]}, legs: {L: [19, 25], R: [19, 25]}},
  {name: "The Sneaky Scarecrow", emoji: "🎃", tip: "Squat down, cross your arms overhead, and lean right!", difficulty: 3, arms: {L: [209, 210], R: [209, 210]}, legs: {L: [42, -13], R: [42, -13]}, lean: 7},
  {name: "The Glorious Starfish", emoji: "⭐", tip: "Squat down, arms low and wide!", difficulty: 2, arms: {L: [37, 43], R: [37, 43]}, legs: {L: [39, -17], R: [39, -17]}},
  {name: "The Cosmic Mantis", emoji: "🦗", tip: "Squat down, reach for the stars, and lean right!", difficulty: 2, arms: {L: [174, 178], R: [174, 178]}, legs: {L: [43, -17], R: [43, -17]}, lean: 7},
  {name: "The Angry Robot", emoji: "🤖", tip: "Squat down, one arm up, one out!", difficulty: 2, arms: {L: [165, 174], R: [91, 88]}, legs: {L: [38, -18], R: [38, -18]}},
  {name: "The Legendary Pretzel", emoji: "🥨", tip: "Squat down, tilt your wings!", difficulty: 2, arms: {L: [67, 68], R: [107, 115]}, legs: {L: [32, -9], R: [32, -9]}},
  {name: "The Wobbly Gremlin", emoji: "👹", tip: "Squat down, arms up in a V, and lean right!", difficulty: 2, arms: {L: [154, 135], R: [154, 135]}, legs: {L: [36, -18], R: [36, -18]}, lean: 7},
  {name: "The Spicy Kettle", emoji: "☕", tip: "Squat down, arms low and wide!", difficulty: 2, arms: {L: [45, 45], R: [45, 45]}, legs: {L: [42, -16], R: [42, -16]}},
  {name: "The Majestic Broccoli", emoji: "🥦", tip: "Squat down, flex those biceps!", difficulty: 2, arms: {L: [95, 215], R: [95, 215]}, legs: {L: [33, -18], R: [33, -18]}},
  {name: "The Dramatic Jellyfish", emoji: "🪼", tip: "Squat down, cross your arms overhead, and lean right!", difficulty: 3, arms: {L: [207, 218], R: [207, 218]}, legs: {L: [38, -15], R: [38, -15]}, lean: 9},
  {name: "The Sleepy Lobster", emoji: "🦞", tip: "Squat down, arms low and wide!", difficulty: 2, arms: {L: [46, 49], R: [46, 49]}, legs: {L: [34, -12], R: [34, -12]}},
  {name: "The Lazy Penguin", emoji: "🐧", tip: "Goddess squat, knees way out, arms low and wide!", difficulty: 2, arms: {L: [46, 43], R: [46, 43]}, legs: {L: [55, -24], R: [55, -24]}},
  {name: "The Cosmic Sasquatch", emoji: "🦶", tip: "Goddess squat, knees way out, one arm up, one out, and lean right!", difficulty: 3, arms: {L: [162, 171], R: [89, 89]}, legs: {L: [48, -23], R: [48, -23]}, lean: 7},
  {name: "The Wonky Meerkat", emoji: "🐿️", tip: "Goddess squat, knees way out, hands on hips, and lean left!", difficulty: 3, arms: {L: [54, -32], R: [54, -32]}, legs: {L: [48, -22], R: [48, -22]}, lean: -6},
  {name: "The Chaotic Starfish", emoji: "⭐", tip: "Goddess squat, knees way out, one flex, one sky-point!", difficulty: 3, arms: {L: [95, 211], R: [155, 164]}, legs: {L: [57, -21], R: [57, -21]}},
  {name: "The Glorious Llama", emoji: "🦙", tip: "Goddess squat, knees way out, cross your arms overhead!", difficulty: 3, arms: {L: [202, 218], R: [202, 218]}, legs: {L: [57, -30], R: [57, -30]}},
  {name: "The Haunted Windmill", emoji: "🌀", tip: "Goddess squat, knees way out, arms up in a V!", difficulty: 2, arms: {L: [136, 154], R: [136, 154]}, legs: {L: [55, -21], R: [55, -21]}},
  {name: "The Crispy Disco Ball", emoji: "🪩", tip: "Goddess squat, knees way out, arms straight out!", difficulty: 2, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [58, -31], R: [58, -31]}},
  {name: "The Confused Pretzel", emoji: "🥨", tip: "Goddess squat, knees way out, tilt your wings, and lean right!", difficulty: 3, arms: {L: [70, 74], R: [114, 115]}, legs: {L: [55, -23], R: [55, -23]}, lean: 9},
  {name: "The Glorious Disco Ball", emoji: "🪩", tip: "Goddess squat, knees way out, one arm up, one out!", difficulty: 3, arms: {L: [89, 88], R: [166, 174]}, legs: {L: [58, -19], R: [58, -19]}},
  {name: "The Heroic Gremlin", emoji: "👹", tip: "Goddess squat, knees way out, zigzag arms!", difficulty: 3, arms: {L: [92, 11], R: [91, 168]}, legs: {L: [57, -30], R: [57, -30]}},
  {name: "The Legendary Ninja", emoji: "🥷", tip: "Foot tucked to your knee, hands on hips, and lean left!", difficulty: 3, arms: {L: [52, -38], R: [52, -38]}, legs: {L: [59, -59], R: [1, 2]}, lean: -7},
  {name: "The Confused Disco Ball", emoji: "🪩", tip: "Foot tucked to your knee, arms straight out, and lean left!", difficulty: 3, arms: {L: [90, 91], R: [90, 91]}, legs: {L: [61, -58], R: [1, 2]}, lean: -7},
  {name: "The Slippery Cactus", emoji: "🌵", tip: "Foot tucked to your knee, goalpost arms!", difficulty: 2, arms: {L: [95, 173], R: [95, 173]}, legs: {L: [2, 4], R: [61, -60]}},
  {name: "The Suspicious Lobster", emoji: "🦞", tip: "Foot tucked to your knee, arms low and wide!", difficulty: 2, arms: {L: [50, 40], R: [50, 40]}, legs: {L: [67, -55], R: [2, 2]}},
  {name: "The Turbo Goose", emoji: "🪿", tip: "Foot tucked to your knee, arms straight out!", difficulty: 2, arms: {L: [89, 91], R: [89, 91]}, legs: {L: [63, -58], R: [2, 3]}},
  {name: "The Cosmic Broccoli", emoji: "🥦", tip: "Foot tucked to your knee, arms straight out!", difficulty: 2, arms: {L: [90, 90], R: [90, 90]}, legs: {L: [4, 3], R: [61, -55]}},
  {name: "The Sneaky Cactus", emoji: "🌵", tip: "Foot tucked to your knee, arms low and wide!", difficulty: 2, arms: {L: [49, 45], R: [49, 45]}, legs: {L: [1, 4], R: [61, -51]}},
  {name: "The Grumpy Pretzel", emoji: "🥨", tip: "Foot tucked to your knee, arms straight out, and lean left!", difficulty: 3, arms: {L: [91, 91], R: [91, 91]}, legs: {L: [1, 1], R: [63, -49]}, lean: -6},
  {name: "The Bendy Llama", emoji: "🦙", tip: "Foot tucked to your knee, point to the sky, hand on hip!", difficulty: 3, arms: {L: [50, -35], R: [157, 159]}, legs: {L: [61, -48], R: [3, 1]}},
  {name: "The Grumpy Penguin", emoji: "🐧", tip: "Foot tucked to your knee, reach for the stars!", difficulty: 2, arms: {L: [173, 176], R: [173, 176]}, legs: {L: [66, -62], R: [1, 2]}},
  {name: "The Bendy Disco Ball", emoji: "🪩", tip: "Foot tucked to your knee, point to the sky, hand on hip!", difficulty: 3, arms: {L: [156, 157], R: [54, -34]}, legs: {L: [64, -51], R: [2, 3]}},
  {name: "The Galactic Yeti", emoji: "❄️", tip: "Foot tucked to your knee, goalpost arms, and lean right!", difficulty: 3, arms: {L: [92, 169], R: [92, 169]}, legs: {L: [66, -51], R: [1, 2]}, lean: 7},
  {name: "The Chaotic Traffic Cone", emoji: "🚧", tip: "Knee up high, flex those biceps, and lean right!", difficulty: 3, arms: {L: [94, 215], R: [94, 215]}, legs: {L: [89, 10], R: [4, 5]}, lean: 6},
  {name: "The Awkward Wizard", emoji: "🧙", tip: "Knee up high, reach for the stars, and lean right!", difficulty: 3, arms: {L: [176, 175], R: [176, 175]}, legs: {L: [89, 12], R: [4, 3]}, lean: 6},
  {name: "The Wonky Toad", emoji: "🐸", tip: "Knee up high, arms low and wide!", difficulty: 2, arms: {L: [50, 45], R: [50, 45]}, legs: {L: [83, 4], R: [5, 4]}},
  {name: "The Glorious Penguin", emoji: "🐧", tip: "Knee up high, goalpost arms!", difficulty: 2, arms: {L: [91, 163], R: [91, 163]}, legs: {L: [95, 8], R: [5, 2]}},
  {name: "The Feral Broccoli", emoji: "🥦", tip: "Knee up high, reach for the stars!", difficulty: 2, arms: {L: [174, 173], R: [174, 173]}, legs: {L: [88, 9], R: [3, 3]}},
  {name: "The Grumpy Lobster", emoji: "🦞", tip: "Knee up high, one flex, one sky-point!", difficulty: 3, arms: {L: [151, 156], R: [91, 213]}, legs: {L: [3, 4], R: [90, 5]}},
  {name: "The Feral Scarecrow", emoji: "🎃", tip: "Knee up high, flex those biceps!", difficulty: 2, arms: {L: [95, 210], R: [95, 210]}, legs: {L: [5, 5], R: [88, 14]}},
  {name: "The Disco Traffic Cone", emoji: "🚧", tip: "Knee up high, arms straight out!", difficulty: 2, arms: {L: [88, 92], R: [88, 92]}, legs: {L: [83, 8], R: [4, 2]}},
  {name: "The Awkward Tornado", emoji: "🌪️", tip: "Knee up high, goalpost arms!", difficulty: 2, arms: {L: [94, 168], R: [94, 168]}, legs: {L: [88, 12], R: [4, 4]}},
  {name: "The Confused Yeti", emoji: "❄️", tip: "Knee up high, one flex, one sky-point!", difficulty: 3, arms: {L: [152, 156], R: [94, 210]}, legs: {L: [4, 4], R: [88, 8]}},
  {name: "The Angry Goose", emoji: "🪿", tip: "Knee up high, arms low and wide, and lean left!", difficulty: 3, arms: {L: [41, 51], R: [41, 51]}, legs: {L: [92, 9], R: [4, 3]}, lean: -7},
  {name: "The Grumpy Banana", emoji: "🍌", tip: "Knee up high, point to the sky, hand on hip, and lean left!", difficulty: 3, arms: {L: [151, 158], R: [52, -32]}, legs: {L: [3, 4], R: [91, 5]}, lean: -6},
  {name: "The Bendy Toad", emoji: "🐸", tip: "Kick a leg out to the side, point to the sky, hand on hip!", difficulty: 3, arms: {L: [156, 160], R: [59, -34]}, legs: {L: [83, 80], R: [5, 3]}},
  {name: "The Royal Yeti", emoji: "❄️", tip: "Kick a leg out to the side, goalpost arms!", difficulty: 3, arms: {L: [94, 170], R: [94, 170]}, legs: {L: [3, 5], R: [73, 78]}},
  {name: "The Electric Windmill", emoji: "🌀", tip: "Kick a leg out to the side, arms low and wide!", difficulty: 3, arms: {L: [36, 42], R: [36, 42]}, legs: {L: [86, 74], R: [4, 4]}},
  {name: "The Galactic Pirate", emoji: "🏴‍☠️", tip: "Kick a leg out to the side, hands on hips!", difficulty: 3, arms: {L: [59, -35], R: [59, -35]}, legs: {L: [3, 4], R: [84, 88]}},
  {name: "The Disco Llama", emoji: "🦙", tip: "Kick a leg out to the side, cross your arms overhead!", difficulty: 3, arms: {L: [203, 216], R: [203, 216]}, legs: {L: [77, 74], R: [3, 3]}},
  {name: "The Tipsy Jellyfish", emoji: "🪼", tip: "Kick a leg out to the side, one flex, one sky-point!", difficulty: 3, arms: {L: [88, 205], R: [150, 164]}, legs: {L: [81, 75], R: [3, 3]}},
  {name: "The Wobbly Traffic Cone", emoji: "🚧", tip: "Kick a leg out to the side, arms straight out!", difficulty: 3, arms: {L: [91, 92], R: [91, 92]}, legs: {L: [4, 3], R: [83, 80]}},
  {name: "The Lazy Ninja", emoji: "🥷", tip: "Kick a leg out to the side, cross your arms overhead!", difficulty: 3, arms: {L: [207, 212], R: [207, 212]}, legs: {L: [5, 6], R: [77, 76]}},
  {name: "The Dramatic Gremlin", emoji: "👹", tip: "Kick a leg out to the side, reach for the stars!", difficulty: 3, arms: {L: [168, 173], R: [168, 173]}, legs: {L: [6, 3], R: [83, 71]}},
  {name: "The Electric Giraffe", emoji: "🦒", tip: "Kick a leg out to the side, goalpost arms!", difficulty: 3, arms: {L: [91, 164], R: [91, 164]}, legs: {L: [6, 3], R: [86, 87]}},
  {name: "The Dramatic Banana", emoji: "🍌", tip: "Cross your legs, tilt your wings, and lean right!", difficulty: 3, arms: {L: [66, 68], R: [114, 111]}, legs: {L: [-12, -16], R: [-27, -26]}, lean: 6},
  {name: "The Electric Starfish", emoji: "⭐", tip: "Cross your legs, arms up in a V!", difficulty: 2, arms: {L: [156, 140], R: [156, 140]}, legs: {L: [-13, -14], R: [-24, -29]}},
  {name: "The Turbo Scarecrow", emoji: "🎃", tip: "Cross your legs, arms up in a V!", difficulty: 2, arms: {L: [159, 165], R: [159, 165]}, legs: {L: [-13, -16], R: [-23, -28]}},
  {name: "The Turbo Robot", emoji: "🤖", tip: "Cross your legs, flex those biceps!", difficulty: 2, arms: {L: [97, 202], R: [97, 202]}, legs: {L: [-15, -17], R: [-24, -25]}},
  {name: "The Royal Lobster", emoji: "🦞", tip: "Cross your legs, goalpost arms!", difficulty: 2, arms: {L: [93, 171], R: [93, 171]}, legs: {L: [-15, -18], R: [-27, -24]}},
  {name: "The Feral Ninja", emoji: "🥷", tip: "Cross your legs, tilt your wings!", difficulty: 3, arms: {L: [116, 110], R: [63, 67]}, legs: {L: [-14, -17], R: [-27, -28]}},
  {name: "The Dramatic Kettle", emoji: "☕", tip: "Cross your legs, flex those biceps, and lean right!", difficulty: 3, arms: {L: [99, 210], R: [99, 210]}, legs: {L: [-14, -15], R: [-25, -25]}, lean: 10},
  {name: "The Glorious Lobster", emoji: "🦞", tip: "Cross your legs, arms straight out!", difficulty: 2, arms: {L: [92, 90], R: [92, 90]}, legs: {L: [-14, -17], R: [-23, -28]}},
  {name: "The Haunted Lobster", emoji: "🦞", tip: "Half lunge, tilt your wings!", difficulty: 2, arms: {L: [114, 120], R: [72, 66]}, legs: {L: [31, -9], R: [8, 8]}},
  {name: "The Spooky Llama", emoji: "🦙", tip: "Half lunge, arms low and wide!", difficulty: 2, arms: {L: [38, 48], R: [38, 48]}, legs: {L: [34, -10], R: [6, 7]}},
  {name: "The Mystic Tornado", emoji: "🌪️", tip: "Half lunge, one flex, one sky-point!", difficulty: 2, arms: {L: [91, 212], R: [158, 153]}, legs: {L: [31, -8], R: [9, 9]}},
  {name: "The Crispy Kettle", emoji: "☕", tip: "Half lunge, one flex, one sky-point!", difficulty: 2, arms: {L: [91, 207], R: [154, 165]}, legs: {L: [28, -13], R: [7, 6]}},
  {name: "The Tipsy Heron", emoji: "🐦", tip: "Half lunge, arms up in a V!", difficulty: 2, arms: {L: [132, 157], R: [132, 157]}, legs: {L: [28, -10], R: [10, 7]}},
  {name: "The Sneaky Banana", emoji: "🍌", tip: "Half lunge, zigzag arms!", difficulty: 2, arms: {L: [88, 169], R: [89, 6]}, legs: {L: [31, -10], R: [7, 9]}},
  {name: "The Awkward Lobster", emoji: "🦞", tip: "Half lunge, tilt your wings, and lean right!", difficulty: 3, arms: {L: [67, 65], R: [113, 108]}, legs: {L: [33, -10], R: [6, 7]}, lean: 6},
  {name: "The Bendy Scarecrow", emoji: "🎃", tip: "Half lunge, tilt your wings!", difficulty: 2, arms: {L: [61, 71], R: [110, 112]}, legs: {L: [27, -13], R: [9, 8]}},
];
